title: Just the Docs Exercise
description: Just the Docs exercise
theme: just-the-docs

url: https://kataszczes.github.io/just-the-docs

aux_links:
  Template Repository: https://github.com/kataszczes/just-the-docs

footer_content: "This is a footer"
heading_anchors: true
