title: Just the Docs Exercise
description: Just the Docs exercise
theme: just-the-docs

url: https://kataszczes.github.io/just-the-docs

aux_links:
  Template Repository: https://github.com/kataszczes/just-the-docs

footer_content: "Fajny footer. TO MÓWIŁEM JA JARZĄBEK"
heading_anchors: true
favicon_ico: "/images/favicon.ico"
search_enabled: true
